### PR TITLE
#41: Fix deriveRoute macro (closes #41)

### LINKED ISSUE #41: Fix deriveRoute macro
## requirements
- `deriveRoute` macro fails if no `path` is defined on the controller
- Fix deriveRoute macro

## specs
{optional: describe technical specs to implement this feature, if not obvious}

## misc
{optional: other useful info}

### PR DESCRIPTION
**Pull request by calippo**
Closes #41

### tests performed
- compiled locally

### CODE REVIEW

File: serverAkkaHttp/src/main/scala/RouterDerivation.scala [hunk 1]
```diff
@@ -14,12 +15,22 @@ object RouterDerivationMacro extends RouterDerivationMacro {
     import c.universe._
     val tpe = weakTypeOf[A]
 
+    //check only annotations of path type
```
Comment (bytecodeguru) [inline serverAkkaHttp/src/main/scala/RouterDerivation.scala:18]: This kind of comment calls out for "introduce method" to improve readability. ;-)

**Review by bytecodeguru — APPROVED** [review]
Just a suggestion to improve readability. Thumbs up for the rest. 👍
