### PR TITLE
#106: Dead code warning when setting a default for routes parameters (closes #106)

### LINKED ISSUE #106: Dead code warning when setting a default for routes parameters
## description
```
@path("products")
trait ProductsController {

  @query
  def read(
    ascending: Boolean = true,
  ): Future[Either[ApiError, List[Book]]]
}
```

```
[warn] /Users/matteo/Documents/Buildo/cryptonite/api/src/main/scala/cryptonite/Boot.scala:31:56: dead code following this construct
[warn]   val productsRouter = deriveRouter[ProductsController](new ProductsControllerImpl(productsService))
```

## how to reproduce
- {optional: describe steps to reproduce defect}

## specs
{optional: describe a possible fix for this defect, if not obvious}

## misc
{optional: other useful info}

### PR DESCRIPTION
**Pull request by calippo**
Closes #106

## Test Plan

> These results can be screenshots, query results, or even just pointers to unit tests that successfully passed.}

> An example of partial test is a field displaying 4 possible values. If 3 values are tested, with screenshots, and 1 is not, then it should be mentioned here.}

### CODE REVIEW

File: core/src/main/scala/MetaDataMacro.scala [hunk 1]
```diff
@@ -36,9 +36,9 @@ object MetaDataMacro extends MetaDataMacro {
           case opAnnotation if opAnnotation.tree.tpe <:< weakTypeOf[query] =>
             val name = opAnnotation.tree.children.tail.head
             q"OperationType.Query($name)"
-        }
+        }.getOrElse(EmptyTree)
 
-        q"($methodName -> $operationType.map { o => MethodMetaData(o) })"
+        q"($methodName -> Some(MethodMetaData($operationType)))"
```
Comment (gabro) [inline core/src/main/scala/MetaDataMacro.scala]: Instead of doing `getOrElse` and then rewrapping, you can do

```scala
$operationType.map(MethodMetaData(_)).orElse(Some(EmptyTree))
```

or

```scala
val operationType = m.annotations.collectFirst {
  // ...
}.orElse(Some(EmptyTree))

q"($methodName -> $operationType.map(MethodMetadata(_)))"
```

File: core/src/main/scala/MetaDataMacro.scala [hunk 2]
```diff
@@ -39,9 +39,9 @@ object MetaDataMacro extends MetaDataMacro {
             q"_root_.wiro.OperationType.Query($name)"
         }
 
-        q"($methodName -> $operationType.map { o => _root_.wiro.MethodMetaData(o) })"
+        q"($methodName -> $operationType.map(_root_.wiro.MethodMetaData(_)))"
     }
 
-    q"Map(..$decls) collect { case (k, Some(v)) => (k -> v) }"
+    q"_root_.scala.collection.immutable.Map(..$decls) collect { case (k, Some(v)) => (k -> v) }"
```
Comment (gabro) [inline core/src/main/scala/MetaDataMacro.scala:45]: this is for hygiene.
