### PR TITLE
#125: Wiro is logging unncessary stuff (closes #125)

### LINKED ISSUE #125: Wiro is logging unncessary stuff
## description
Wiro is logging unncessary stuff.

## how to reproduce
- {optional: describe steps to reproduce defect}

## specs
{optional: describe a possible fix for this defect, if not obvious}

## misc
{optional: other useful info}

### PR DESCRIPTION
**Pull request by calippo**
Closes #125

## Test Plan

> These results can be screenshots, query results, or even just pointers to unit tests that successfully passed.}

> An example of partial test is a field displaying 4 possible values. If 3 values are tested, with screenshots, and 1 is not, then it should be mentioned here.}

### CODE REVIEW

File: serverAkkaHttp/src/main/scala/RPCRouter.scala [hunk 1]
```diff
@@ -35,7 +35,7 @@ trait Router extends RPCServer with PathMacro with MetaDataMacro with LazyLoggin
 
   def exceptionHandler = ExceptionHandler {
     case e: FailException[_] =>
-      logger.error(e.getMessage, e)
+      logger.error(s"encoding error: ${e.getMessage}")
```
Comment (gabro) [inline serverAkkaHttp/src/main/scala/RPCRouter.scala:38]: add the stacktrace for debugging?

**Review by gabro — CHANGES_REQUESTED** [review]

File: serverAkkaHttp/src/main/scala/RPCRouter.scala (hunk 1 above)
Comment (calippo) [reply serverAkkaHttp/src/main/scala/RPCRouter.scala:38]: The stacktrace looks like this: it's not super-informative.

41228175-ba668f30-6d77-11e8-89ab-b9ee9a01c11a

This error comes from autowire encoding (this is enforced by the type). The message is inherited from autowire.

I agree this is not a super-clean solution but:
1. The stacktrace is not useful (it's also a little annoying in bobafett)
2. I don't have better solutions at the moment

This is not solving the root issue (`null` 😡). We can spend some more time to understand that.
It doesn't seem to cause real issues though.

Comment (gabro) [reply serverAkkaHttp/src/main/scala/RPCRouter.scala:38]: 👍

**Review by gabro — APPROVED** [review]

**Review by albertocoletta — APPROVED** [review]
